name: Test
on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint

  Test:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: [ '16.13.0', '18.x', '19.x' ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
